//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace xBRIMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BridgeInfo
    {
        public long BridgeID { get; set; }
        public string ChnAfairsCenter { get; set; }
        public string LocArea { get; set; }
        public string ChnName { get; set; }
        public string StartPoint { get; set; }
        public string EndPoint { get; set; }
        public string Mileage { get; set; }
        public string ChnDeptBridgeName { get; set; }
        public string TrnDeptBridgeName { get; set; }
        public string RawDeptBridgeName { get; set; }
        public string HgwDeptartmentBridgeName { get; set; }
        public string OtherBridgeName { get; set; }
        public string ChnMainLevel { get; set; }
        public string ChnTechLevel { get; set; }
        public string ChnPlanLevel { get; set; }
        public string NavMarkDistCate { get; set; }
        public string ChnDegnDeptth { get; set; }
        public string ChnMainDeptth { get; set; }
        public string MainDeptthRate { get; set; }
        public string LocRegion { get; set; }
        public string BridgeLoc { get; set; }
        public string BridgeCoor { get; set; }
        public string CrossRiver { get; set; }
        public string ApproNavHoles { get; set; }
        public string ActualNavHoles { get; set; }
        public string UpApproSpan { get; set; }
        public string UpActualSpan { get; set; }
        public string UpApproWidth { get; set; }
        public string UpActualWidth { get; set; }
        public string UpApproHeight { get; set; }
        public string UpActualHeight { get; set; }
        public string DownApproSpan { get; set; }
        public string DownActualSpan { get; set; }
        public string DownApproWidth { get; set; }
        public string DownActualWidth { get; set; }
        public string DownApproHeight { get; set; }
        public string DownActualHeight { get; set; }
        public string ApproMaxWaterLevel { get; set; }
        public string StdMaxWaterLevel { get; set; }
        public string AdopDesgMaxWaterLevel { get; set; }
        public string StdDesgMaxWaterLevel { get; set; }
        public string UpBottomWidth { get; set; }
        public string DownBottomWidth { get; set; }
        public string UpSideHeight { get; set; }
        public string DownSideHeight { get; set; }
        public string DegnMinWaterLevel { get; set; }
        public string DegnStdMinWaterLevel { get; set; }
        public string WaterLevelRefSource { get; set; }
        public string ApproDocNum { get; set; }
        public string ImpNavStd { get; set; }
        public string CompleDate { get; set; }
        public string SpecialAccep { get; set; }
        public string ApproStdLevelReq { get; set; }
        public string CurrLevelReq { get; set; }
        public string TechLevelReq { get; set; }
        public string PlanLevelReq { get; set; }
        public string BridgeSpans { get; set; }
        public string bridgePillarLights { get; set; }
        public string WaterwayMarks { get; set; }
        public string HeightScaleSet { get; set; }
        public string otherNavMarks { get; set; }
        public string MarkMainDept { get; set; }
        public string MarkSetAppro { get; set; }
        public string MarkSpecReq { get; set; }
        public string BridgeCate { get; set; }
        public string BridgeMgmtDept { get; set; }
        public string BridgeStrucType { get; set; }
        public string BridgeMgmtConPerson { get; set; }
        public string ContactInfo { get; set; }
        public string BridgeCol5Years { get; set; }
        public string AntiColMgmtDept { get; set; }
        public string IsAntiCol { get; set; }
        public string AntiColStrucType { get; set; }
        public string AntiColNum { get; set; }
        public string AntiColStd { get; set; }
        public string IsActWarnSys { get; set; }
        public string HeightDisplay { get; set; }
        public string HeightDisplayChnDept { get; set; }
        public string HeightDisplayTrnCent { get; set; }
        public string HeightDisplayStatus { get; set; }
        public string BridgeStatus { get; set; }
        public string Remark { get; set; }
        public string BridgePhoto01 { get; set; }
        public string BridgePhoto02 { get; set; }
        public string BridgePhoto03 { get; set; }
        public string BridgePhoto04 { get; set; }
        public string BridgePhoto05 { get; set; }
        public string BridgePhoto06 { get; set; }
        public string Bakup01 { get; set; }
        public string Bakup02 { get; set; }
        public string Bakup03 { get; set; }
        public string Bakup04 { get; set; }
        public string Bakup05 { get; set; }
        public string Bakup06 { get; set; }
        public string Bakup07 { get; set; }
        public string Bakup08 { get; set; }
        public string Bakup09 { get; set; }
        public string Bakup10 { get; set; }
    }
}
