//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace xBRIMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NavigationInfo
    {
        public long NavigationID { get; set; }
        public string DamNavStrucType { get; set; }
        public string DamName { get; set; }
        public string ChnName { get; set; }
        public string ChnCurrStatus { get; set; }
        public string ChnPlanStatus { get; set; }
        public string DamLocation { get; set; }
        public string BuiltYear { get; set; }
        public string Scale { get; set; }
        public string HasDam { get; set; }
        public string DamRegistInd { get; set; }
        public string DamRegistYear { get; set; }
        public string DamSafeEvalInd { get; set; }
        public string DamSafeEvalYear { get; set; }
        public string DamSafeEvalRusult { get; set; }
        public string DamOperDept { get; set; }
        public string DamOperDeptResp { get; set; }
        public string Capacity { get; set; }
        public string DamType { get; set; }
        public string DamMaxHeight { get; set; }
        public string DamTopEle { get; set; }
        public string CheckFloodLvl { get; set; }
        public string CheckFloodYear { get; set; }
        public string DesignFloodLvl { get; set; }
        public string DesignFloodYear { get; set; }
        public string NorWaterLvl { get; set; }
        public string LimWaterLvl { get; set; }
        public string DamRegDept { get; set; }
        public string hasLock { get; set; }
        public string LockLevel { get; set; }
        public string LockScale { get; set; }
        public string UpMaxWaterLvl { get; set; }
        public string UpStdMaxWaterLvl { get; set; }
        public string UpMinWaterLvl { get; set; }
        public string UpStdMinWaterLvl { get; set; }
        public string DownMaxWaterLvl { get; set; }
        public string DownStdMaxWaterLvl { get; set; }
        public string DownMinWaterLvl { get; set; }
        public string DownStdMinWaterLvl { get; set; }
        public string LockOperDept { get; set; }
        public string LockOperDeptResp { get; set; }
        public string LockRegDept { get; set; }
        public string RegDeptResp { get; set; }
        public string LockSafeEval { get; set; }
        public string LockSafeEvalYear { get; set; }
        public string LockSafeEvalResult { get; set; }
        public string LockNavStatus { get; set; }
        public string Near1to3YPass { get; set; }
        public string StruTechStatus { get; set; }
        public string HasApprOpSch { get; set; }
        public string Notes { get; set; }
        public string Photo01 { get; set; }
        public string Photo02 { get; set; }
        public string Photo03 { get; set; }
        public string Photo04 { get; set; }
        public string Photo05 { get; set; }
        public string Photo06 { get; set; }
        public string Backup01 { get; set; }
        public string Backup02 { get; set; }
        public string Backup03 { get; set; }
        public string Backup04 { get; set; }
        public string Backup05 { get; set; }
        public string Backup06 { get; set; }
        public string Backup07 { get; set; }
        public string Backup08 { get; set; }
        public string Backup09 { get; set; }
        public string Backup10 { get; set; }
    }
}
